import { appendFile, mkdir } from "node:fs/promises";
import { spawn } from "node:child_process";
import path from "node:path";

const logDir = path.resolve("work", "update-logs");
const logFile = path.join(logDir, `${new Date().toISOString().slice(0, 10)}.log`);

async function log(message) {
  await mkdir(logDir, { recursive: true });
  await appendFile(logFile, `[${new Date().toISOString()}] ${message}\n`);
}

function run(command, args) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { shell: true, stdio: "inherit" });
    child.on("exit", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${command} ${args.join(" ")} exited with ${code}`));
    });
  });
}

async function main() {
  await log("Catalog update started");
  await run("npm", ["run", "generate:data"]);
  await log("Verified movie data regenerated");
  await run("npm", ["run", "build"]);
  await log("Static build completed; sitemap and RSS generated by Next.js export");
  await log("Deploy step is handled by Cloudflare Pages after this workflow succeeds");
}

main().catch(async (error) => {
  await log(`Catalog update failed: ${error.message}`);
  process.exit(1);
});
